---
chapter: False
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Dynverse

**dynverse** is a collection of R packages aimed at supporting the trajectory inference (TI) community on multiple levels: end-users who want to apply TI on their dataset of interest, and developers who seek to easily quantify the performance of their TI method and compare it to other TI methods.

All of these packages were developed as part of a benchmarking study available on [bioRxiv](https://doi.org/10.1101/276907). All source code has been made available in the [dynbenchmark](https://github.com/dynverse/dynbenchmark) repository.

<blockquote class="citation">
<p>
  <strong>A comparison of single-cell trajectory inference methods</strong>
</p>
<p>
  <span class="wt"></span><span class="rc"></span>Helena Todorov, Yvan Saeys.
</p>
<p>
  [Nature Biotechnology (In press) doi:10.1038/s41587-019-0071-9](https://doi.org/10.1038/s41587-019-0071-9).
</p>
<p>
  [bioRxiv (Mar. 2018) doi:10.1101/276907](https://doi.org/10.1101/276907). <span data-badge-popover="bottom" data-badge-type="bar" data-doi="doi:10.1101/276907" data-hide-no-mentions="true" class="altmetric-embed"></span><script async type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script><span class="__dimensions_badge_embed__" data-doi="10.1101/276907" data-style="small_rectangle" data-legend="hover-bottom"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script><style> .__dimensions_badge_embed__{display:inline!important;}</style>
</p>
</blockquote>

## End-users
The **[dyno](/users)** package offers **end-users** a complete TI pipeline. It features:

* a uniform interface to 50+ [TI methods](https://github.com/dynverse/dynmethods#list-of-included-methods),
* an [interactive guideline tool](https://github.com/dynverse/dyno#selecting-the-most-optimal-ti-methods) to help the user select the most appropriate method, 
* the [interpretation and visualisation of trajectories](https://github.com/dynverse/dyno#plotting-the-trajectory), including colouring by gene expression or clusters, and
* downstream analyses such as the [identification of potential marker genes](https://github.com/dynverse/dyno#plotting-relevant-features).

## Developers
For developers of existing or new TI methods, **dyno** offers the same features as to end-users. In addition, developers might also want to check out the following packages:

* **[dynmethods](https://github.com/dynverse/dynmethods)**, which is a repository of wrappers for TI methods. If your method has already been included in dynmethods, an [issue](https://github.com/dynverse/dynmethods/issues) will have been created there. 
* **[dynwrap](https://github.com/dynverse/dynwrap)**, the wrapping functions for transforming common trajectory data formats into the common trajectory model supported by dynverse.
* **[dynbenchmark](https://github.com/dynverse/dynbenchmark)**, all source code in order to replicate the benchmarking study by Saelens and Cannoodt ([10.1101/276907](https://doi.org/10.1101/276907)).
* Check out this [overview of all dynverse packages](/reference) for more information of the functionality of each package.




<!-- Switch wt and rc -->
<style>
.wt:before{
  content: '';
  animation: wt 10s linear infinite;
}

@keyframes wt {
  0% {opacity:0; content: "Wouter Saelens*, "}
  5% {opacity:1; }
  45% {opacity:1; }
  50% {opacity:0; content: "Wouter Saelens*, "}
  51% {opacity:0; content: "Robrecht Cannoodt*, "}
  55% {opacity:1; }
  95% {opacity:1; }
  99% {opacity:0; content: "Robrecht Cannoodt*, "}
  100% {opacity:0; content: "Wouter Saelens*, "}
}

.rc:before{
  content: '';
  animation: rc 10s linear infinite;
}

@keyframes rc {
    0% {opacity:0; content: "Robrecht Cannoodt*, "}
    5% {opacity:1; content: "Robrecht Cannoodt*, "}
    45% {opacity:1; content: "Robrecht Cannoodt*, "}
    50% {opacity:0; content: "Robrecht Cannoodt*, "}
    51% {opacity:0; content: "Wouter Saelens*, "}
    55% {opacity:1; content: "Wouter Saelens*, "}
    95% {opacity:1; content: "Wouter Saelens*, "}
    99% {opacity:0; content: "Wouter Saelens*, "}
    100% {opacity:0; content: "Robrecht Cannoodt*, "}
}
</style>
